name: Update Github Pages


'on':
  push:
    branches:
      - main

jobs:
  update-resume-pages:
    runs-on: ubuntu-22.04
    permissions:
      # This makes sure that this action has permissions to push to
      # the gh-pages branch.
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v6
      - uses: DeterminateSystems/magic-nix-cache-action@v7

      - run: |
          nix build . -L

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: './result/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
